// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Standardized env var: VITE_SUPABASE_ANON_KEY (matches service files)
// Also supports legacy VITE_SUPABASE_PUBLISHABLE_KEY for backward compatibility
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "";

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn(
    "Supabase environment variables are missing (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY). " +
    "Database features will be unavailable \u2014 the app will use local storage fallback."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_URL && SUPABASE_ANON_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null;

/**
 * Helper to check if Supabase is available. Services should call this
 * before attempting DB operations and fall back to localStorage if false.
 */
export function isSupabaseAvailable(): boolean {
  return supabase !== null;
}
